id: P005517
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:55:59.000961
source_metadata:
  id: bdr:W1KG17210
  title: དག་ལྡན་མཆན་འགྲེལ་རྒྱུད་དོན་གསལ་བའི་སྤྱན་ཤེལ།
  author: ''
  volumes:
    9c1e4c107a22444995dc8d9c56486623:
      image_group_id: I1KG17638
      title: ''
      volume_number: 1
      total_pages: 298
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
