id: P005517
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17210
  title: དག་ལྡན་མཆན་འགྲེལ་རྒྱུད་དོན་གསལ་བའི་སྤྱན་ཤེལ།
  author: ''
  volumes:
    9c1e4c107a22444995dc8d9c56486623:
      image_group_id: I1KG17638
      title: ''
      volume_number: 1
      total_pages: 298
      base_file: v001.txt
