id: I7D6FD072
legacy_id: P005517
ocr_import_info:
  bdrc_scan_id: W1KG17210
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T12:13:05'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T06:26:51.034083+00:00'
last_modified: 2022-08-27 14:27:26.228519
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG17210
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG17210
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དག་ལྡན་མཆན་འགྲེལ་རྒྱུད་དོན་གསལ་བའི་སྤྱན་ཤེལ།
  author: འཛམ་ཐང་མཁན་པོ་ངག་དབང་ཡོན་ཏན་བཟང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.9650402711950845
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG17638:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17638
      total_pages: 298
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG17638.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9650402711950845
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
